defaults:
  - pipeline: unet
  - _self_

dataset: nmsc-2x

data_processed_root: ???
runs_dir: ???

dataset_root: ${data_processed_root}/${dataset}

fast_dev_run: false

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
